# Generated by Django 6.0.1 on 2026-02-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('book_name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(choices=[('Science', 'Science'), ('Computer', 'Computer'), ('Literature', 'Literature'), ('Management', 'Management')], max_length=50)),
            ],
        ),
    ]
