# Generated by Django 6.0.1 on 2026-02-03 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pustak', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='isbn_number',
        ),
    ]
